### ISSUE TITLE
Show the list of available versions on mouseover

### ISSUE THREAD

**Issue by washanhanzi** [washanhanzi/cargo-appraiser#2]

**Comment by Alphapage** [comment]
It would be great if we could click the requested version to update cargo.toml instead of going back and use the keyboard.

**Comment by washanhanzi** [comment]
Hmm, the refactor and update process currently is done with `Code Action`, something like this:
![CleanShot 2025-01-16 at 15 24 41@2x](https://github.com/user-attachments/assets/0d3773fc-35a5-453f-9647-48b3cbc5aef7)

https://code.visualstudio.com/docs/editor/refactoring
 
 If you have other requirements not list in the current code action, let me know.

**Comment by Alphapage** [comment]
Ok, I was expecting to be able to click an item in the list, but code action is enough 👍

**Comment by washanhanzi** [comment]
I will check it later. But I don't think VSCode let me run command on mouse click of the hover content.
