### ISSUE TITLE
list of issues

### ISSUE THREAD

**Issue by frederik-uni** [washanhanzi/cargo-appraiser#22]
- api overuse(reached maximum after 4/5 times opening the Cargo.toml
   - possible fixes: caching, daemon, use registry instead of api `https://doc.rust-lang.org/cargo/reference/registries.html`
- git inlay hint should compare hashes instead of versions
- git inlay hint should show hashes & version
- hover features works only over the values not the keys
- panicked

```
stderr: called `Result::unwrap()` on an `Err` value: Error("invalid node cannot be serialized", line: 0, column: 0)
stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr: error sending changed event: channel closed
stderr: Failed to send Ctx: channel closed
stderr: thread 'main' panicked at src/main.rs:125:14:
stderr: called `Result::unwrap()` on an `Err` value: SendError { .. }
```

Btw I plan to take inspiration with the hover feature (& the inlay hints, but this was planed anyway). I hope this doesn't bother you.

**Comment by washanhanzi** [comment]
Thanks for the feedback. I am still in the process to figure out how to properly implement the code completion and diagnostic. The existing features haven't been tailored. And I haven't start to improve the code quality, there are a lot of unwrap which cause the panic. I also take inspiration from your cargotom :).

**Comment by frederik-uni** [comment]
my bad. the api overuse was a vpn issue. doesn't change the fact that the registry & caching would improve performance.

**Comment by washanhanzi** [comment]
- now dependency from git will show commit hash in inlay hint
- hover on version and features key will show corresponding information
- stability improved
